### Create a 6X6 NumPy array with random integers between 1 and 50.

In [2]:
import numpy as np

# using the random numpy function to generate random nums from 1 to 50
new_range = np.random.randint(1, 50, (6, 6))
new_range

array([[30, 45, 28, 38,  2, 44],
       [20,  9, 23, 40,  1, 16],
       [28, 35, 43, 41, 30, 27],
       [39,  3, 34, 25, 27, 10],
       [ 2, 27, 31, 15, 14,  2],
       [46, 11, 37,  7, 17, 34]], dtype=int32)

### Extract the following:
- The first two rows

In [3]:
ext1 = new_range[0:2, 0:]

ext1

array([[30, 45, 28, 38,  2, 44],
       [20,  9, 23, 40,  1, 16]], dtype=int32)

- The last three columns

In [4]:
ext2 = new_range[0:, -3:]

ext2

array([[38,  2, 44],
       [40,  1, 16],
       [41, 30, 27],
       [25, 27, 10],
       [15, 14,  2],
       [ 7, 17, 34]], dtype=int32)

- All even numbers

In [5]:
even_nums = new_range[new_range % 2 == 0]

even_nums

array([30, 28, 38,  2, 44, 20, 40, 16, 28, 30, 34, 10,  2, 14,  2, 46, 34],
      dtype=int32)

- Reshape into a 3D (3, 2, 6) array

In [6]:
new_shape = new_range.reshape(3, 2, 6)

new_shape

array([[[30, 45, 28, 38,  2, 44],
        [20,  9, 23, 40,  1, 16]],

       [[28, 35, 43, 41, 30, 27],
        [39,  3, 34, 25, 27, 10]],

       [[ 2, 27, 31, 15, 14,  2],
        [46, 11, 37,  7, 17, 34]]], dtype=int32)

- Flatten the reshaped array into a 1D array

In [7]:
flatten_arr = new_shape.flatten()

flatten_arr

array([30, 45, 28, 38,  2, 44, 20,  9, 23, 40,  1, 16, 28, 35, 43, 41, 30,
       27, 39,  3, 34, 25, 27, 10,  2, 27, 31, 15, 14,  2, 46, 11, 37,  7,
       17, 34], dtype=int32)

- Generate a 4X4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10

In [8]:
# np.diag(np.arange(10, 50, 10))

# Create a 2D array with what you specify as the diagonal and zeros on the rest
identity_matrix = np.eye(4, dtype=int)

# Replace the diagonal with a new one from range 10 to 40, with a step of 10
np.fill_diagonal(identity_matrix, np.arange(10, 41, 10))

print(identity_matrix)


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


- Perform matrix multiplication between: A 3X4 matrix of random integers (1-10) and A 4X3 matix of random integers (1-10)

In [9]:
matrix_one = np.random.randint(1, 10, (3, 4))
matrix_two = np.random.randint(1, 10, (4, 3))
matrixmul = np.matmul(matrix_one, matrix_two)

matrixmul

array([[ 97, 103, 111],
       [ 94,  95,  91],
       [127,  98, 143]], dtype=int32)

Create a function that takes a 2D NumPy array as input and returns a new array where:
- All even numbers are squared
- All odd numbers are replaced by -1

In [ ]:
def arr_matrix():
  # Take the input for rows and columns from the user
  x = int(input("Please enter the number of rows: "))
  y = int(input("Please enter the number of columns: "))

  # Create a 2D NumPy array using the input from the user
  arr = np.arange(x * y).reshape(x, y)

  # Using the where function, return the squared even numbers and replace the odd numbers by -1
  new_arr = np.where(arr % 2 == 0, arr**2, -1)
  print(new_arr)
  
  # Output is a row of 3 and column of 4
  
arr_matrix()

[[  0  -1   4  -1]
 [ 16  -1  36  -1]
 [ 64  -1 100  -1]]
