## Problem Setup

We have the scores of 4 students in 3 subjects (Mathematics, English, Science):

Represented as 

\begin{bmatrix}
Students & Maths & English & Science \\
1 & 80 & 70 & 90 \\
2 & 60 & 85 & 75 \\
3 & 95 & 88 & 92 \\
4 & 70 & 60 & 65 \\
\end{bmatrix} 

with Students represented as the rows and Subjects (Maths, English and Science) represented as columns respectively

**Total Scores per Student (Vector Addition)**

\begin{bmatrix}
Students  & Calc(Total)  & Total  \\
1 & 80 + 70 + 90 & 240 \\
2 & 60 + 85 + 75 & 220 \\
3 & 95 + 88 + 95 & 275 \\
4 & 70 + 60 + 65 & 195 \\
\end{bmatrix} 


In [2]:
import numpy as np 

# Represent the students scores as an array of rows of students and columns of subjects
students_scores = np.array([[80, 70, 90], 
                            [60, 85, 75], 
                            [95, 88, 92], 
                            [70, 60, 65]])

# Calculating the first student's total scores
student1_total_scores = students_scores[0, :].sum()
print(f"Student 1 Total Score: {student1_total_scores}")

# Calculating student 2 total scores
student2_total_scores = students_scores[1, :].sum()
print(f"Student 2 Total Score: {student2_total_scores}")

# Calculating student 3 total scores
student3_total_scores = students_scores[2, :].sum()
print(f"Student 3 Total Score: {student3_total_scores}")

# Calculating student 2 total scores
student4_total_scores = students_scores[3, :].sum()
print(f"Student 4 Total Score: {student4_total_scores}")

Student 1 Total Score: 240
Student 2 Total Score: 220
Student 3 Total Score: 275
Student 4 Total Score: 195


**Applying Weights (Scalar Multiplication)**
Using Maths being twice as important

    Maths =  2 x   [[80]
                    [60]
                    [95]
                    [70]]

\begin{bmatrix}
160  \\
120 \\
190  \\
140  \\
\end{bmatrix} 

In [3]:
scalar = 2
scores_transpose = students_scores.T
scores_transpose

# The first row in this case represents the subject Maths
maths_2_scores = scalar * scores_transpose[0, :]
print("The sum of twice the sum of all the students scores in Maths: ", maths_2_scores)

The sum of twice the sum of all the students scores in Maths:  [160 120 190 140]


**Average Score per Subject (Matrix Operations)**

Since the number of students are 4

To get the average of each student we multiple each row by 1/4

<!-- 80 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65 \\ -->
    Average = 1/4 x  [[80, 70, 90]
                      [60, 85, 75]
                      [95, 88, 92]
                      [70, 60, 65]]

\begin{bmatrix}
Subject & Calc(Average) & Average \\
Maths & (80 + 60 + 95 + 70) * 1/4 & 76.25 \\
English & (70 + 85 + 88 + 60) * 1/4 & 75.75 \\
Science & (90 + 75 + 92 + 65) * 1/4 & 80.5 \\
\end{bmatrix} 


In [4]:
# Average Score of Mathematics
maths_average = students_scores[:, 0].mean()
print(f"The Average of Maths: {maths_average}")

english_average = students_scores[:, 1].mean()
print(f"The Average of English: {english_average}")

science_average = students_scores[:, 2].mean()
print(f"The Average of English: {science_average}")

The Average of Maths: 76.25
The Average of English: 75.75
The Average of English: 80.5


**Final Grades using Matrix Multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades**

To attempt the scalar multiplication, we need the number of columns of the data to be equal to the number of rows of the weight vector

\begin{bmatrix}
80 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65 \\
\end{bmatrix}

\begin{bmatrix}         
0.5  \\                 
0.3 \\                  
0.2  \\                 
\end{bmatrix}

\begin{bmatrix}         
(0.5 * 80) + (0.3 * 70) + (0.2 * 90) \\                 
(0.5 * 60) + (0.3 * 85) + (0.2 * 75) \\                 
(0.5 * 95) + (0.3 * 88) + (0.2 * 92) \\                 
(0.5 * 70) + (0.3 * 60) + (0.2 * 65) \\                          
\end{bmatrix}

\begin{bmatrix}         
40 + 21 + 18 \\                 
30 + 25.5 + 15 \\                 
47.5 + 26.4 + 18.4 \\                 
35 + 18 + 13 \\                          
\end{bmatrix}

\begin{bmatrix}         
79 \\                 
70.5 \\                 
92.3 \\                 
66 \\                          
\end{bmatrix}

In [9]:
# The data of students as rows and subjects as columns, we have a 4x3
# The transpose of the Weight Vector is a 3x1 matrix, this is so that it is compatible for scalar multiplication

weight_vector = np.array([[0.5], 
                          [0.3], 
                          [0.2]])

# This makes it compatible
# Calculating final grades using numpy's dot or @
final_grades = np.dot(students_scores, weight_vector)

# OR

final_grades2 = students_scores @ weight_vector

# Result is a 4x1 matrix
dimension = final_grades2.shape


print("Final Grades: \n", final_grades)
print("Final Grades: \n", final_grades2)
print("Dimension", dimension)

Final Grades: 
 [[79. ]
 [70.5]
 [92.3]
 [66. ]]
Final Grades: 
 [[79. ]
 [70.5]
 [92.3]
 [66. ]]
Dimension (4, 1)


**Comparing Students(Vector Subtraction)**

\begin{bmatrix}
Student & Maths & English & Science \\
1 & 80 & 70 & 90 \\
2 & 60 & 85 & 75 \\
\end{bmatrix}

        Comparing student 1 and student 2
                    Student 1     -    Student 2
        Average = [80, 70, 90]    -   [60, 85, 75]


\begin{bmatrix}
Subject & Student1 - Student2 \\
Maths & 80 - 60 \\
English & 70 - 85 \\
Science & 90 - 75 \\
\end{bmatrix}

\begin{bmatrix}
Subject & Comparison \\
Maths & 20 \\
English & -15 \\
Science & 25 \\
\end{bmatrix}

In [12]:
student1 = students_scores[0, :]
print("Student 1 and scores: \n", student1)

student2 = students_scores[1, :]
print("Student 2 and scores: \n", student2)

# Comparing student 1 and student 2
comparison = student1 - student2
print("Comparing Student1 and Student2: \n", comparison)

Student 1 and scores: 
 [80 70 90]
Student 2 and scores: 
 [60 85 75]
Comparing Student1 and Student2: 
 [ 20 -15  15]
