In [7]:
import numpy as np

# Given two matrices

A = np.array([[2, -1],
                     [0, 3]])

B = np.array([[1, 4],
                     [-2, 5]])

# And two Scalars
c = 2
d = 3

**1. Compute cA, dB and (c + d)A**

In [8]:
# Use numpy to multiply scalar_c with vector_A
cA = c * A

# Use numpy to multiply scalar_d with vector_B
dB = d * B

# Use numpy to compute (c + d)A
right_associate = (c + d) * A

print(f"Computed cA:\n {cA}")
print(f"Computed dB:\n {dB}")
print(f"Associative:\n {right_associate}")

Computed cA:
 [[ 4 -2]
 [ 0  6]]
Computed dB:
 [[ 3 12]
 [-6 15]]
Associative:
 [[10 -5]
 [ 0 15]]


**2. Using the results gotten, Verify the Scalar Multiplication Properties**

In [12]:
# 1. Associativity
# (c . d)A = c . (dA)

left_associativity = (c * d) * A
print("Left associativity:\n", left_associativity)

right_associativity = c * (d * A)
print("Right associativity:\n", right_associativity)

print(f"Associative: {np.array_equal(left_associativity, right_associativity)}")


Left associativity:
 [[12 -6]
 [ 0 18]]
Right associativity:
 [[12 -6]
 [ 0 18]]
Associative: True


In [14]:
# 2. Distributivity over Matrix Addition
# c(A + B) = cA + cB

left_distributivity = c * (A + B)
print("Left Distributivity:\n", left_distributivity)

right_distributivity = (c * A) + (c * B)
print("Right Distributivity:\n", right_distributivity)

print(f"Distributive over matrix addition: {np.array_equal(left_distributivity, right_distributivity)}")

Left Distributivity:
 [[ 6  6]
 [-4 16]]
Right Distributivity:
 [[ 6  6]
 [-4 16]]
Distributive over matrix addition: True


In [15]:
# 3. Distributivity over Scalar Addition
# (c + d)A = cA + dA

left_sa_distributive = (c + d) * A
print("Left Distributivity:\n", left_sa_distributive)

right_sa_distributive = (c * A) + (d * A)
print("Right Distributivity:\n", right_sa_distributive)

print(f"Distributive over matrix addition: {np.array_equal(left_sa_distributive, right_sa_distributive)}")

Left Distributivity:
 [[10 -5]
 [ 0 15]]
Right Distributivity:
 [[10 -5]
 [ 0 15]]
Distributive over matrix addition: True


**3. Find the transpose of both matrices**

In [18]:
transpose_of_A = A.T
print("Transpose of A: \n", transpose_of_A)

transpose_of_B = B.T
print("Transpose of B: \n", transpose_of_B)


Transpose of A: 
 [[ 2  0]
 [-1  3]]
Transpose of B: 
 [[ 1 -2]
 [ 4  5]]


**4. Check if A and B are invertible by computing their determinant, if so, find the inverse of A and the inverse of B**

In [19]:
# Find the determinant of A
print("Determinant |A|:\n", np.linalg.det(A))

Determinant |A|:
 6.0


In [20]:
# Since the determinant of A is not 0
# Get the inverse
print("Inverse of A:\n", np.linalg.inv(A))

Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


In [21]:
# Find the determinant of B
print("Determinant |B|:\n", np.linalg.det(B))

Determinant |B|:
 13.0


In [22]:
# Since the determinant of B is not 0
# Get the inverse
print("Inverse of B:\n", np.linalg.inv(B))

Inverse of B:
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
