## Problem Setup

We have the scores of 4 students in 3 subjects (Mathematics, English, Science):

Represented as 

\begin{bmatrix}
Students & Maths & English & Science \\
1 & 80 & 70 & 90 \\
2 & 60 & 85 & 75 \\
3 & 95 & 88 & 92 \\
4 & 70 & 60 & 65 \\
\end{bmatrix} 

with Students represented as the rows and Subjects (Maths, English and Science) represented as columns respectively

**Total Scores per Student (Vector Addition)**

\begin{bmatrix}
Students  & Calc(Total)  & Total  \\
1 & 80 + 70 + 90 & 240 \\
2 & 60 + 85 + 75 & 220 \\
3 & 95 + 88 + 95 & 275 \\
4 & 70 + 60 + 65 & 195 \\
\end{bmatrix} 


In [2]:
import numpy as np 

# Represent the students scores as an array of rows of students and columns of subjects
students_scores = np.array([[80, 70, 90], 
                            [60, 85, 75], 
                            [95, 88, 92], 
                            [70, 60, 65]])

# Calculating the first student's total scores
student1_total_scores = students_scores[0, :].sum()
print(f"Student 1 Total Score: {student1_total_scores}")

# Calculating student 2 total scores
student2_total_scores = students_scores[1, :].sum()
print(f"Student 2 Total Score: {student2_total_scores}")

# Calculating student 3 total scores
student3_total_scores = students_scores[2, :].sum()
print(f"Student 3 Total Score: {student3_total_scores}")

# Calculating student 2 total scores
student4_total_scores = students_scores[3, :].sum()
print(f"Student 4 Total Score: {student4_total_scores}")

Student 1 Total Score: 240
Student 2 Total Score: 220
Student 3 Total Score: 275
Student 4 Total Score: 195


**Applying Weights (Scalar Multiplication)**
Using Maths being twice as important

    Maths =  2 x [80, 60, 95, 70]

\begin{bmatrix}
160  \\
120 \\
190  \\
140  \\
\end{bmatrix} 

In [3]:
scalar = 2
scores_transpose = students_scores.T
scores_transpose

# The first row in this case represents the subject Maths
maths_2_scores = scalar * scores_transpose[0, :]
print("The sum of twice the sum of all the students scores in Maths: ", maths_2_scores)

The sum of twice the sum of all the students scores in Maths:  [160 120 190 140]


**Average Score per Subject (Matrix Operations)**

Since the number of students are 4

To get the average of each student we multiple each row by 1/4

<!-- 80 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65 \\ -->
    Average = 1/4 x  [[80, 70, 90]
                      [60, 85, 75]
                      [95, 88, 92]
                      [70, 60, 65]]

\begin{bmatrix}
Subject & Calc(Average) & Average \\
Maths & (80 + 60 + 95 + 70) * 1/4 & 76.25 \\
English & (70 + 85 + 88 + 60) * 1/4 & 75.75 \\
Science & (90 + 75 + 92 + 65) * 1/4 & 80.5 \\
\end{bmatrix} 


In [4]:
# Average Score of Mathematics
maths_average = students_scores[:, 0].mean()
print(f"The Average of Maths: {maths_average}")

english_average = students_scores[:, 1].mean()
print(f"The Average of English: {english_average}")

science_average = students_scores[:, 2].mean()
print(f"The Average of English: {science_average}")

The Average of Maths: 76.25
The Average of English: 75.75
The Average of English: 80.5


**Final Grades using Matrix Multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades**

To attempt the scalar multiplication, we need the number of columns of the data to be equal to the number of rows of the weight vector (The weight will be an array of 3x1) and since the student data is a 4x3, it is compatible for scalar multiplication

\begin{bmatrix}
80 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65 \\
\end{bmatrix}

\begin{bmatrix}         
0.5  \\                 
0.3 \\                  
0.2  \\                 
\end{bmatrix}

\begin{bmatrix}         
(0.5 * 80) + (0.3 * 70) + (0.2 * 90) \\                 
(0.5 * 60) + (0.3 * 85) + (0.2 * 75) \\                 
(0.5 * 95) + (0.3 * 88) + (0.2 * 92) \\                 
(0.5 * 70) + (0.3 * 60) + (0.2 * 65) \\                          
\end{bmatrix}

\begin{bmatrix}         
40 + 21 + 18 \\                 
30 + 25.5 + 15 \\                 
47.5 + 26.4 + 18.4 \\                 
35 + 18 + 13 \\                          
\end{bmatrix}

\begin{bmatrix}         
79 \\                 
70.5 \\                 
92.3 \\                 
66 \\                          
\end{bmatrix}

In [5]:
# The data of students as rows and subjects as columns, we have a 4x3
# The transpose of the Weight Vector is a 3x1 matrix, this is so that it is compatible for scalar multiplication

weight_vector = np.array([[0.5], 
                          [0.3], 
                          [0.2]])

# This makes it compatible
# Calculating final grades using numpy's dot or @
final_grades = np.dot(students_scores, weight_vector)

# OR

final_grades2 = students_scores @ weight_vector

# Result is a 4x1 matrix
dimension = final_grades2.shape


print("Final Grades: \n", final_grades)
print("Final Grades: \n", final_grades2)
print("Dimension", dimension)

Final Grades: 
 [[79. ]
 [70.5]
 [92.3]
 [66. ]]
Final Grades: 
 [[79. ]
 [70.5]
 [92.3]
 [66. ]]
Dimension (4, 1)


**Comparing Students(Vector Subtraction)**

\begin{bmatrix}
Student & Maths & English & Science \\
1 & 80 & 70 & 90 \\
2 & 60 & 85 & 75 \\
\end{bmatrix}

        Comparing student 1 and student 2
                    Student 1     -    Student 2
        Average = [80, 70, 90]    -   [60, 85, 75]


\begin{bmatrix}
Subject & Student1 - Student2 \\
Maths & 80 - 60 \\
English & 70 - 85 \\
Science & 90 - 75 \\
\end{bmatrix}

\begin{bmatrix}
Subject & Comparison & Who did better? \\
Maths & 20 & Student 1 \\
English & -15 & Student 2 \\
Science & 25 & Student 1 \\
\end{bmatrix}

In [ ]:
student1 = students_scores[0, :]
print("Student 1 and scores: \n", student1)

student2 = students_scores[1, :]
print("Student 2 and scores: \n", student2)

# Comparing student 1 and student 2
comparison = student1 - student2
print("Comparing Student1 and Student2: \n", comparison)

# From the data we can that Student 1 did better in Subjects Maths and Science. Student 2 did better in English.

Student 1 and scores: 
 [80 70 90]
Student 2 and scores: 
 [60 85 75]
Comparing Student1 and Student2: 
 [ 20 -15  15]


## ADD ON EXERCISES

**Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total score and the average per subject.**

We have the scores of 5 students in 4 subjects (Mathematics, English, Chemistry, Biology):

Represented as 

\begin{bmatrix}
Students & Maths & English & Chemistry & Biology \\
Mary & 85 & 65 & 80 & 75 \\
James & 75 & 85 & 75 & 90 \\
Henry & 95 & 88 & 80 & 70 \\
Kola & 70 & 60 & 65 & 84 \\
Musa & 92 & 80 & 75 & 88 
\end{bmatrix} 

with Students represented as the rows and Subjects (Maths, English and Chemistry and Biology) represented as columns respectively

    mary_total_scores = 85 + 65 + 80 + 75 = 305
    james_total_scores = 75 + 85 + 75 + 90 = 325
    henry_total_scores = 95 + 88 + 80 + 70 = 333
    kola_total_scores = 70 + 60 + 65 + 84 = 279
    musa_total_scores = 92 + 80 + 75 + 88 = 335

students_total_scores = 

\begin{bmatrix}
Students & Calc(Scores) & Total Score \\
Mary & 85 + 65 + 80 + 75 & 305 \\
James & 75 + 85 + 75 + 90 & 325 \\
Henry & 95 + 88 + 80 + 70 & 333 \\
Kola & 70 + 60 + 65 + 84 & 279 \\
Musa & 92 + 80 + 75 + 88 & 335 
\end{bmatrix} 

To get the average of each subject we need to transpose and multiply by 1/4 as 4 is the total subject

<!-- array([[85, 75, 95, 70, 92],
       [65, 85, 88, 60, 80],
       [80, 75, 80, 65, 75],
       [75, 90, 70, 84, 88]]) -->

    1/4 * [[85, 75, 95, 70, 92],
            [65, 85, 88, 60, 80],
            [80, 75, 80, 65, 75],
            [75, 90, 70, 84, 88]]
    
Subjects Average = 

\begin{bmatrix}
Subjects & Calc(Average) & Average \\
Maths & (85 + 75 + 95 + 70 + 92) * 1/4 & 83.4 \\
English & (65 + 85 + 88 + 60 + 80) * 1/4 & 75.6 \\
Chemistry & (80 + 75 + 80 + 65 + 75) * 1/4 & 75 \\
Biology & (75 + 90 + 70 + 84 + 88) * 1/4 & 81.4 \\
\end{bmatrix} 

    

In [27]:
# Using numpy
student_scores2 = np.array([[85, 65, 80, 75],
                            [75, 85, 75, 90],
                            [95, 88, 80, 70],
                            [70, 60, 65, 84],
                            [92, 80, 75, 88]])

mary_total_scores = student_scores2[0, :].sum()
print("Mary's Total Score:", mary_total_scores)

james_total_scores = student_scores2[1, :].sum()
print("James' Total Score:", james_total_scores)

henry_total_scores = student_scores2[2, :].sum()
print("Henry's Total Score:", henry_total_scores)

kola_total_scores = student_scores2[3, :].sum()
print("Kola's Total Score:", kola_total_scores)

musa_total_scores = student_scores2[4, :].sum()
print("Musa's Total Score:", musa_total_scores)

# Average Per Subject
print("=" * 100)

maths_average = student_scores2[:, 0].mean()
print("Maths Average: ", maths_average)

english_average = student_scores2[:, 1].mean()
print("English Average: ", english_average)

chemistry_average = student_scores2[:, 2].mean()
print("Chemistry Average: ", chemistry_average)

biology_average = student_scores2[:, 3].mean()
print("Biology Average: ", biology_average)


Mary's Total Score: 305
James' Total Score: 325
Henry's Total Score: 333
Kola's Total Score: 279
Musa's Total Score: 335
Maths Average:  83.4
English Average:  75.6
Chemistry Average:  75.0
Biology Average:  81.4


**2. Suppose one subject (e.g., Chemistry) is 3 times more important than others. Apply scalar multiplication and recompute totals.**

    Maths =  3 x  [80, 75, 80, 65, 75]

\begin{bmatrix}
240  \\
225 \\
240  \\
195  \\
225  \\
\end{bmatrix} 

In [23]:
# Using numpy
scalar = 3

# Getting Chemistry subject from the vector
chemistry_scores = student_scores2[:, 2]
chemistry_scores

chemistry_3times_scores = 3 * chemistry_scores
print("Chemistry being 3 times more important \n", chemistry_3times_scores)

Chemistry being 3 times more important 
 [240 225 240 195 225]


**3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using matrix multiplication.**

To attempt the scalar multiplication, we need the number of columns of the data to be equal to the number of rows of the weight vector (The weight will be an array of 4x1) and since the student data is a 5x4, it is compatible for scalar multiplication

**Student Data**
\begin{bmatrix}
85 & 65 & 80 & 75 \\
75 & 85 & 75 & 90 \\
95 & 88 & 80 & 70 \\
70 & 60 & 65 & 84 \\
92 & 80 & 75 & 88 \\
\end{bmatrix}

**Weight Vector**
\begin{bmatrix}         
0.4  \\                 
0.2 \\                  
0.3  \\                 
0.1  \\                 
\end{bmatrix}

\begin{bmatrix}         
(0.4 * 85) + (0.2 * 65) + (0.3 * 80) + (0.1 * 75) \\                 
(0.4 * 75) + (0.2 * 85) + (0.3 * 75) + (0.1 * 90) \\                 
(0.4 * 95) + (0.2 * 88) + (0.3 * 80) + (0.1 * 70) \\                 
(0.4 * 70) + (0.2 * 60) + (0.3 * 65) + (0.1 * 84) \\                          
(0.4 * 92) + (0.2 * 80) + (0.3 * 75) + (0.1 * 88) \\                          
\end{bmatrix}

\begin{bmatrix}         
34 + 13 + 24 + 7.5 \\                 
30 + 17 + 22.5 + 9 \\                 
38 + 17.6 + 24 + 7 \\                 
28 + 12 + 19.5 + 8.4 \\                          
36.8 + 16 + 22.5 + 8.8 \\                          
\end{bmatrix}

\begin{bmatrix}         
78.5 \\                 
78.5 \\                 
86.6 \\                 
67.9 \\                          
84.1 \\                          
\end{bmatrix}

In [24]:
grading_weights = [[0.4],
                   [0.2],
                   [0.3],
                   [0.1]]

# Multiplying the student data by the weight grading

final_grades3 = np.dot(student_scores2, grading_weights)

print("Student Final Grades: \n", final_grades3)

# The result dimension should be a 5x1 matrix
# Calculating final grades using numpy's dot or @

final_grades4 = student_scores2 @ grading_weights

# Result is a 4x1 matrix
dimension = final_grades4.shape
print("the resulting dimension: ", dimension)

Student Final Grades: 
 [[78.5]
 [78.5]
 [86.6]
 [67.9]
 [84.1]]
the resulting dimension:  (5, 1)


**4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each subject?**

    student3 = [95, 88, 80, 70]
    student4 = [70, 60, 65, 84]

    comparison = [(95 - 70), (88 - 60), (80 - 65), (70 - 84)]
    comparison = [25, 28, 25, -14] 

\begin{bmatrix}         
Comparison & Subject & Who Did Better \\                 
25 & Maths & student 3 \\                 
28 & English & student 3 \\                 
25 & Chemistry & student 3 \\                          
-14 & Biology & student 4 \\                          
\end{bmatrix}

In [25]:
student3 = student_scores2[2, :]
student4 = student_scores2[3, :]

comparison = student3 - student4
comparison
# From the data student 3 did better in all the subjects apart from Biology which shows that student 4 did better

array([ 25,  28,  15, -14])