### Create a 6X6 NumPy array with random integers between 1 and 50.

In [ ]:
import numpy as np

# us
new_range = np.random.randint(1, 50, (6, 6))
new_range

array([[27,  3, 43, 47, 44, 10],
       [16,  2, 21, 26, 22, 12],
       [46,  8, 48, 13, 23, 48],
       [ 5, 22, 29,  4, 49,  9],
       [41, 40, 43, 45, 14, 14],
       [25, 30, 34, 12, 36,  1]], dtype=int32)

### Extract the following:
- The first two rows

In [9]:
ext1 = new_range[0:2, 0:]

ext1

array([[27,  3, 43, 47, 44, 10],
       [16,  2, 21, 26, 22, 12]], dtype=int32)

- The last three columns

In [11]:
ext2 = new_range[0:, -3:]

ext2

array([[47, 44, 10],
       [26, 22, 12],
       [13, 23, 48],
       [ 4, 49,  9],
       [45, 14, 14],
       [12, 36,  1]], dtype=int32)

- All even numbers

In [62]:
even_nums = new_range[new_range % 2 == 0]

even_nums

array([44, 10, 16,  2, 26, 22, 12, 46,  8, 48, 48, 22,  4, 40, 14, 14, 30,
       34, 12, 36], dtype=int32)

- Reshape into a 3D (3, 2, 6) array

In [15]:
new_shape = new_range.reshape(3, 2, 6)

new_shape

array([[[27,  3, 43, 47, 44, 10],
        [16,  2, 21, 26, 22, 12]],

       [[46,  8, 48, 13, 23, 48],
        [ 5, 22, 29,  4, 49,  9]],

       [[41, 40, 43, 45, 14, 14],
        [25, 30, 34, 12, 36,  1]]], dtype=int32)

- Flatten the reshaped array into a 1D array

In [20]:
flatten_arr = new_shape.flatten()

flatten_arr

array([27,  3, 43, 47, 44, 10, 16,  2, 21, 26, 22, 12, 46,  8, 48, 13, 23,
       48,  5, 22, 29,  4, 49,  9, 41, 40, 43, 45, 14, 14, 25, 30, 34, 12,
       36,  1], dtype=int32)

- Generate a 4X4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10

In [58]:
# np.diag(np.arange(10, 50, 10))

identity_matrix = np.eye(4, dtype=int)

np.fill_diagonal(identity_matrix, np.arange(10, 41, 10))

print(identity_matrix)


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


- Perform matrix multiplication between: A 3X4 matrix of random integers (1-10) and A 4X3 matix of random integers (1-10)

In [28]:
matrix_one = np.random.randint(1, 10, (3, 4))
matrix_two = np.random.randint(1, 10, (4, 3))
matrixmul = np.matmul(matrix_one, matrix_two)

matrixmul

array([[102, 162, 126],
       [114, 183, 117],
       [ 81, 134,  77]], dtype=int32)

Create a function that takes a 2D NumPy array as input and returns a new array where:
- All even numbers are squared
- All odd numbers are replaced by -1

In [ ]:
def arr_matrix():
  # 
  x = int(input("Please enter the number of rows: "))
  y = int(input("Please enter the number of columns: "))
  arr = np.arange(x * y).reshape(x, y)
  new_arr = np.where(arr % 2 == 0, arr**2, -1)
  print(new_arr)
  
arr_matrix()

[[  0  -1   4  -1]
 [ 16  -1  36  -1]
 [ 64  -1 100  -1]
 [144  -1 196  -1]
 [256  -1 324  -1]]
