### **Understanding Numpy**

- NumPy (Numerical Python) is the foundation library for scientific computing in Python. It provides a powerful N-dimensional array object and tools for working with these arrays

- Think of NumPy as the engine that powers most data science libraries - pandas uses NumPy arrays internally, scikit-learn expects NumPy arrays for machine learning, and matplotlib uses NumPy for plotting.

- NumPy operations are implemented in C, making them 10-100x faster than pure Python

- NumPy arrays store data more compactly than Python lists

- Vectorization: Perform operations on entire arrays without writing loops

- Work with arrays of different shapes seamlessly

- Foundation for pandas, scikit-learn, matplotlib, and more

In [1]:
# import all necessary libraries

import numpy as np
import matplotlib.pyplot as plt
import time

# Check NumPy version
print(f"NumPy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)

NumPy version: 2.3.2


**Creating Numpy Arrays**

In [2]:
# Creating arrays from Python lists
# ID array: A simple sequence of numbers
arr1d = np.array([1, 2, 3, 4, 5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

# 3D array: Like a stack of 2D arrays - useful for images, time series, etc.
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print("1D array:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Creating Special Arrays in Numpy**

In [3]:
# Creating arrays filled with zeroes - useful for initializing arrays
# Shape (3, 4) means 3 rows and 4 columns
zeroes = np.zeros((3, 4))

# Creating arrays filled with ones - often used as starting points
ones = np.ones((2, 3, 4))     # 3D array: 2 layers, 3 rows, 4 columns

# Empty array - faster than zeros/ones but contains random values 
# Use when you'll immediately fill the array with real data
empty = np.empty((2, 2))

print("Zeros array(3X4):\n", zeroes)
# print("Ones array shape:", ones)
print("Ones array shape:", ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array(3X4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array shape: (2, 3, 4)
Empty array (contains random values):
 [[0. 0.]
 [0. 0.]]


In [6]:
# Range arrays - like Python's range() but more powerful
range_arr = np.arange(0, 10, 2)   # Start, stop, step: [0, 2, 4, 6, 8]
print("Range array:", range_arr)

# Linearly spaced arrays - divide a range into equal parts
# From 0 to 1 with exactly 5 points (including endpoints)
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array: ", linspace_arr)

# Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 2, 5)
print("Logspace array: ", logspace_arr)


Range array: [0 2 4 6 8]
Linspace array:  [0.   0.25 0.5  0.75 1.  ]
Logspace array:  [  1.      3.162  10.     31.623 100.   ]
